modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/AshIndigo/WalkmanMod/issues"
[[mods]]
modId="walkman"
version="${file.jarVersion}"
displayName="Walkman"
displayURL="https://github.com/AshIndigo/WalkmanMod/"
credits="Thanks for this example mod goes to Java" #
authors="AshIndigo"
description='''
Adds a portable disc player to Minecraft!
'''
[[dependencies.walkman]]
    modId="forge" #mandator
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.walkman]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"